### PR TITLE
Operations Documentation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tym-xqo** [comment]
@oaojesse I noticed a few spelling and markdown formatting issues in the OPERATIONS doc. Rather than review them one by one I just added a commit in this branch.

**Comment by ghost** [comment]
@tym-oao I think the language updates that Luz put into the version of this file in the front end server repo would be great to port over here. Agree?

**Comment by tym-xqo** [comment]
@oaojesse Sure. Luz's changes look like a superset of mine, for the most part. I'd be happy to go with her version.

**Comment by luzmcosta** [comment]
@tym-oao @oaojesse This looks ready to merge. What say you?

**Pull request merged**
